# Generated by Django 2.2.7 on 2019-11-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='description',
            field=models.TextField(default='Item description', max_length=1000),
        ),
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.FileField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.Product'),
        ),
    ]
