# Generated by Django 2.2.7 on 2019-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191121_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'detail', 'verbose_name_plural': 'details'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
        migrations.AlterModelOptions(
            name='producttypefeatures',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Item description', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
