# Generated by Django 2.2.6 on 2019-12-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191205_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='productTypeFeatures',
            new_name='feature',
        ),
    ]
