# Generated by Django 2.2.6 on 2019-12-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191206_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='producttype',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType'),
            preserve_default=False,
        ),
    ]
